### ISSUE TITLE
How can i change 3gb file size limit?

### ISSUE THREAD

**Issue by telegrambotdev** [BassThatHertz/AudioAndVideoConverter#14]
i am trying to host this code for myself.so where i have to change for removing 3gb file size limit ?

anyway this project is awsome.add more file type support,for conversion.

Thank you

**Comment by BassThatHertz** [comment]
Remove the following:
- Lines 19 to 21 in main.py
- Lines 60 to 64 in static/js/app.js
> add more file type support,for conversion.

Can you tell me which filetype(s) you need support for? I can look into it.

**Comment by telegrambotdev** [comment]
> Remove the following:
> 
> * Lines 19 to 21 in main.py
> * Lines 60 to 64 in static/js/app.js
> 
> > add more file type support,for conversion.
> 
> Can you tell me which filetype(s) you need support for? I can look into it.

Thanks alot.
i am having problems youtube downloader.converter is working fine.but youtube video downloader is not.

take a look at my logs,line 128,129

https://paste.ubuntu.com/p/KrgrcxFdRx/

the code is running here,take a look

https://heylilly.herokuapp.com/

also your youtube downloader is not working,

when i clicking download
it shows `[object response`] then show intialising`

and nothing happens

**Comment by telegrambotdev** [comment]
*update now your websutes,youtube downloader working fine

**Comment by telegrambotdev** [comment]
i put my youtube_dl_path to `/usr/local/lib/python3.8/dist-packages/youtube_dl`

but not working

**Comment by BassThatHertz** [comment]
1. If you simply run `/usr/local/lib/python3.8/dist-packages/youtube_dl` in the terminal, does it find youtube-dl? 
2. Are you getting the same error message as before> i.e.:
```
2020-10-04T13:03:59.811521+00:00 app[web.1]:   File "/app/yt.py", line 126, in send_json_response
2020-10-04T13:03:59.811524+00:00 app[web.1]:     correct_file = [filename for filename in downloads if video_id in filename and download_type in filename][0]
2020-10-04T13:03:59.811524+00:00 app[web.1]: IndexError: list index out of range
```

**Comment by telegrambotdev** [comment]
luckily i fixed everything,by using another dockerfile.i created my own.
i used 

https://hub.docker.com/r/alfg/ffmpeg/dockerfile

this contain,all prebuilt,ffmpeg settings and then i set everything in my docker,wolah it worked.

bro can you add .vob format too ,for convertion ?

**Comment by BassThatHertz** [comment]
> bro can you add .vob format too ,for convertion ?

Done :)
> do you accept contributions ?

Yes.

**Comment by telegrambotdev** [comment]
> > bro can you add .vob format too ,for convertion ?
> 
> Done :)
> 
> > do you accept contributions ?
> 
> Yes, contributors are more than welcome. Maybe you can improve the Dockerfile/the Docker side of things? I don't know much about Docker at all, another contributor (@retrodaredevil ) created the Dockerfile.

done ☺️

**Comment by telegrambotdev** [comment]
> > bro can you add .vob format too ,for convertion ?
> 
> Done :)
> 
> > do you accept contributions ?
> 
> Yes, contributors are more than welcome. Maybe you can improve the Dockerfile/the Docker side of things? I don't know much about Docker at all, another contributor (@retrodaredevil ) created the Dockerfile.

so i have a question.how long the users uploaded and converted files to be in our server ? fo you set any custom timeframe for auto deletion ? if yes,where is it ? 
if that feature is not yet,our hdd will soon enough.right ? manual deleting is a mess.

**Comment by BassThatHertz** [comment]
@telegrambotdev Here's how space is managed:

**Audio/Video Converter:**

Before the conversion takes place, the following space-saving measures take place:
1. The conversions folder is emptied. Lines 64 to 66 in main.py:
```
        for file in os.listdir('conversions'):
            os.remove(os.path.join('conversions', file))
            log.info(f'Deleted conversions/{file}')
```
2. The size of the uploads folder is checked and if it's larger than 3 GB, it is emptied. Lines 68 to 78 in main.py:
```
        uploads_folder_size = 0
        # Iterate over each file in the folder and add its size to the above variable.
        for file in os.listdir('uploads'):
            size_of_file = os.path.getsize(f'uploads/{file}') / 1_000_000
            uploads_folder_size += size_of_file
        # If there's more than 3 GB of files in the uploads folder, empty it.
        if uploads_folder_size > 3000:
            log.info(f'More than 3 GB worth of uploads found. Emptying uploads folder...')
            for file in os.listdir('uploads'):
                os.remove(os.path.join('uploads', file))
            log.info('Conversions folder emptied.')
```

**YouTube Downloader:**

Before youtube-dl is run, the size of the downloads folder is checked and if it's larger than 3 GB, it is emptied. Lines 178 to 188 in yt.py:
```
        downloads_folder_size = 0

        for file in os.listdir(download_dir):
            # Downloads folder size in MB.
            downloads_folder_size += os.path.getsize(os.path.join(download_dir, file)) / 1_000_000

        if downloads_folder_size > 3000:
            log.info('Downloads folder larger than 3 GB. Emptying the folder...')
            for file in os.listdir(download_dir):
                os.remove(os.path.join(download_dir, file))
            log.info('Downloads folder emptied.')

```
