### ISSUE TITLE
Remote upload file converter

### ISSUE THREAD

**Issue by telegrambotdev** [BassThatHertz/AudioAndVideoConverter#17]
#feature

Can you add url file converter ? like on this website https://audio.online-convert.com/convert/mp4-to-mp3
(like the file will be fetched via,wget method.then it will convert)

This will avoid more data consuming,like if i want to convert a big .vob file on internet and its size is 4gb.instead of downloading that big file in to our local machine,then reupload to our converting website,after convertion then download again.lol see how many uploads and downloads ? instead of that if we implemented an url uploading for convertion,things will be easier.

also people can use our service for compressing the video from a direct link.

Eg: The process works like our website fetches the 4gb file in to the servers upload folder, after convertion,then user can download to their mobile/pc (in 1gb size).

**Comment by BassThatHertz** [comment]
It seems like FFmpeg supports a HTTP URL as input, so adding this option should be pretty trivial. I will probably implement this feature at some point, but I will not mention a timescale as I currently have other priorities in my personal life.

As always, anyone is free to try implementing this themselves. Submit a pull request if you manage to do so successfully.

**Comment by telegrambotdev** [comment]
waiting for the url upload progress too :)

**Comment by BassThatHertz** [comment]
I have added the ability to specify a URL as input. I have only tested this with **https://** URLs. Whether other types of URLs will work simply depends on whether FFmpeg supports that type of URL as input.
